### ISSUE TITLE
Incorrect cluster count on new ClusteredYamap on iOS

### ISSUE THREAD

**Issue by Reeywhaar** [volga-volga/react-native-yamap#179]
When zooming close enough cluster count starts to act strange. Seems it prints total count of all points on a map. Seems to happen only in iOS.

https://user-images.githubusercontent.com/884649/189129771-c80a6a7d-16c7-4f90-9acd-90c969e74401.mov

**Comment by ownikss** [comment]
fixed in 4.1.11

**Comment by Reeywhaar** [comment]
Apparently seems it's not fixed. Same picture in 4.1.11. Even more, I also noticed clusters with wrong count (count here is count of all points on map).

<img width="336" alt="image" src="https://user-images.githubusercontent.com/884649/190116380-5736ea8b-37cb-44c6-b2fd-ca3632be3f7e.png">

**Comment by RuslanAugust** [comment]
Тоже неправильно отображаются счетчики кластеров
<img width="385" alt="Снимок экрана 2023-06-22 в 4 00 34 PM" src="https://github.com/volga-volga/react-native-yamap/assets/64227622/5490ea18-3345-47a8-a3e9-952c548c2982">
